(()=>{
'use strict';
const redeem='https://withhive.me/313/';
const expiredCodes=new Set(['GLHF2026AMERICAS','SWC26X10LEGACYBND']);
const REWARDS={'4READY4TDOT':[['scroll','x1'],['mana','x100'],['energy','x50']],'AUGSW2026V7N':[['scroll-yellow','x1'],['crystal','x100'],['energy','x50']],'SWXFRIEREN2026':[['scroll-blue','x1'],['mana','x100'],['energy','x50']],'LEGENDSWC2026HSL':[['scroll-red','x1'],['crystal','x100'],['energy','x50']],'YIQIZOUGUO10SWC':[['scroll','x1'],['mana','x100'],['energy','x50']]};
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const normalize=c=>String(c).toUpperCase().replace(/[^A-Z0-9]/g,'');
const validCode=c=>{const x=normalize(c);return /^[A-Z0-9]{6,32}$/.test(x)&&/[A-Z]/.test(x)&&/\d/.test(x)&&!expiredCodes.has(x)};
function rewardStyle(){if(document.getElementById('yunamyst-rewards-style'))return;const s=document.createElement('style');s.id='yunamyst-rewards-style';s.textContent=`
.code.auto-code{grid-template-columns:58px minmax(150px,1fr) repeat(3,minmax(65px,82px)) 128px 128px;gap:8px;min-height:103px}
.reward{min-width:0;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:2px;overflow:hidden}.reward-icon{width:40px;height:40px;display:block;filter:drop-shadow(0 2px 3px #0008)}
.reward-icon.scroll,.reward-icon.scroll-yellow,.reward-icon.scroll-blue,.reward-icon.scroll-red{border-radius:9px;transform:rotate(-7deg);background:linear-gradient(135deg,#fff2a6 0 20%,#c67b22 21% 72%,#ffe39a 73%)}.reward-icon.scroll-yellow{background:linear-gradient(135deg,#fff8bb,#f0b42e 50%,#ffe98c)}.reward-icon.scroll-blue{background:linear-gradient(135deg,#e7fbff,#32b9e8 50%,#d9faff)}.reward-icon.scroll-red{background:linear-gradient(135deg,#fff,#e43a31 50%,#ffd8d5)}
.reward-icon.crystal{clip-path:polygon(50% 0,92% 25%,83% 78%,50% 100%,17% 78%,8% 25%);background:linear-gradient(135deg,#ffe7ff,#c238d0 48%,#ffb6f3)}.reward-icon.mana{clip-path:polygon(50% 0,91% 24%,83% 77%,50% 100%,17% 77%,9% 24%);background:linear-gradient(135deg,#9cecff,#168be8 55%,#1248aa)}.reward-icon.energy{width:34px;height:40px;clip-path:polygon(58% 0,12% 56%,45% 56%,35% 100%,88% 37%,55% 37%);background:linear-gradient(135deg,#fff4a0,#ffd21f 48%,#ff9f00)}
.reward b{font-size:12px;line-height:1}.reward small{font-size:8px;color:#d5ccd9;white-space:nowrap}.copy,.link{height:44px!important;width:100%!important;border-radius:9px!important;font-weight:900;font-size:11px!important;display:flex!important;align-items:center;justify-content:center;text-decoration:none;cursor:pointer;touch-action:manipulation}.copy{border:1px solid #edbd4e!important;background:linear-gradient(#f6cd70,#bd7d1d)!important;color:#251400!important}.link{border:1px solid #bba5f4!important;background:#f8f8fb!important;color:#151018!important}
@media(max-width:850px){.code.auto-code{grid-template-columns:44px minmax(0,1fr) minmax(0,1fr) minmax(0,1fr)!important;grid-template-rows:56px 62px 44px!important;grid-template-areas:'gift info info info' 'gift r1 r2 r3' 'copy copy link link'!important;gap:7px!important;padding:11px 8px!important;min-height:174px!important}.code>.gift{grid-area:gift}.code>.cinfo{grid-area:info}.code>.reward:nth-child(3){grid-area:r1}.code>.reward:nth-child(4){grid-area:r2}.code>.reward:nth-child(5){grid-area:r3}.copy{grid-area:copy}.link{grid-area:link}.reward-icon{width:31px;height:31px}.reward-icon.energy{width:28px;height:33px}.reward b{font-size:11px}.reward small{display:none}.cinfo strong{font-size:15px}}
`;document.head.appendChild(s)}
function removeBlockedFromIndex(){const root=document.getElementById('ativos');if(!root)return;root.querySelectorAll('.code').forEach(card=>{const el=card.querySelector('.cinfo strong');if(el&&!validCode(el.textContent))card.remove()})}
function removeStrayMarkupText(){if(!document.body)return;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const bad=[];let n;while(n=walker.nextNode()){const t=(n.nodeValue||'').trim();if(/(?:target\s*=\s*["']?_blank|rel\s*=\s*["']?noopener|noreferrer)/i.test(t))bad.push(n)}bad.forEach(x=>x.nodeValue='')}
function fixBranding(){const styleId='yunamyst-runtime-branding-fix';if(!document.getElementById(styleId)){const s=document.createElement('style');s.id=styleId;s.textContent='.logo .myst-y{font-size:.62em!important;display:inline-block!important;line-height:1!important;vertical-align:baseline!important;transform:translate(-.02em,.05em)!important}@media(max-width:850px){.logo .myst-y{font-size:.58em!important;transform:translate(-.03em,.05em)!important}}';document.head.appendChild(s)}}
function card(code){const rewards=REWARDS[code]||[['scroll','x1'],['mana','x100'],['energy','x50']];const icons=rewards.map(([kind,q])=>`<div class="reward"><span class="reward-icon ${kind}" aria-hidden="true"></span><b>${q}</b></div>`).join('');return `<article class="code auto-code"><div class="gift">🎁</div><div class="cinfo"><strong>${esc(code)}</strong><small>🔄 Código ativo</small></div>${icons}<button class="copy" type="button" data-code="${esc(code)}">▣ COPIAR</button><a class="link" href="${redeem}${encodeURIComponent(code)}" target="_blank" rel="noopener noreferrer">🔗 LINK iOS</a></article>`}
function copyCode(code,b){const old=b.textContent,done=()=>{b.textContent='✓ COPIADO!';setTimeout(()=>b.textContent=old,1500)};if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(code).then(done).catch(()=>fallback(code,b,old));else fallback(code,b,old)}
function fallback(code,b,old){try{const t=document.createElement('textarea');t.value=code;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();if(document.execCommand('copy')){t.remove();doneCopy(b,old);return}t.remove()}catch(e){}window.prompt('Copie o código:',code)}
function doneCopy(b,old){b.textContent='✓ COPIADO!';setTimeout(()=>b.textContent=old,1500)}
function bindCopies(root=document){root.querySelectorAll('.copy[data-code]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',e=>{e.preventDefault();copyCode(b.dataset.code,b)})})}
async function loadCodes(){const active=document.getElementById('ativos');if(!active)return;removeBlockedFromIndex();try{const c=new AbortController(),timer=setTimeout(()=>c.abort(),7000),r=await fetch('./codes.json?ts='+Date.now(),{cache:'no-store',signal:c.signal});clearTimeout(timer);if(!r.ok)throw Error('codes.json');const data=await r.json();const codes=[...new Set((Array.isArray(data.codes)?data.codes:[]).map(normalize).filter(validCode))];if(codes.length)active.innerHTML=codes.map(card).join('');bindCopies(active);removeBlockedFromIndex();const s=document.querySelector('#sectionHead span');if(s)s.textContent='⟳ Atualizado automaticamente'}catch(e){removeBlockedFromIndex();bindCopies(active)}removeStrayMarkupText()}
function setupSound(){const a=document.getElementById('bgMusic'),b=document.getElementById('soundToggle');if(!a||!b||b.dataset.bound)return;b.dataset.bound='1';const key='yunamyst-mute-v3';try{a.muted=localStorage.getItem(key)==='1'}catch(e){}const sync=()=>{b.textContent=a.muted?'🔇':'🔊'};sync();b.addEventListener('click',()=>{a.muted=!a.muted;try{localStorage.setItem(key,a.muted?'1':'0')}catch(e){}if(!a.muted)a.play().catch(()=>{});sync()})}
function init(){rewardStyle();fixBranding();setupSound();bindCopies();loadCodes()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
