(()=>{
'use strict';
const redeem='https://withhive.me/313/';
// Bloqueio definitivo: estes códigos não podem ser mostrados, mesmo que
// uma fonte antiga ou um cache volte a devolvê-los.
const expiredCodes=new Set(['GLHF2026AMERICAS','SWC26X10LEGACYBND']);
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const normalize=c=>String(c).toUpperCase().replace(/[^A-Z0-9]/g,'');
const validCode=c=>{const x=normalize(c);return /^[A-Z0-9]{6,32}$/.test(x)&&/[A-Z]/.test(x)&&/\d/.test(x)&&!expiredCodes.has(x)};
function removeBlockedFromIndex(){
  const root=document.getElementById('ativos');
  if(!root)return;
  root.querySelectorAll('.code').forEach(card=>{
    const el=card.querySelector('.cinfo strong');
    if(el&&expiredCodes.has(normalize(el.textContent)))card.remove();
  });
}
function removeStrayMarkupText(){if(!document.body)return;const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const bad=[];let n;while(n=walker.nextNode()){const t=(n.nodeValue||'').trim();if(/(?:target\s*=\s*["']?_blank|rel\s*=\s*["']?noopener|noreferrer)/i.test(t))bad.push(n)}bad.forEach(x=>x.nodeValue='')}
function fixBranding(){const styleId='yunamyst-runtime-branding-fix';if(!document.getElementById(styleId)){const s=document.createElement('style');s.id=styleId;s.textContent='.logo .myst-y{font-size:.62em!important;display:inline-block!important;line-height:1!important;vertical-align:baseline!important;transform:translate(-.02em,.05em)!important}.social-links .social-btn{color:inherit!important;text-decoration:none!important}@media(max-width:850px){.logo .myst-y{font-size:.58em!important;transform:translate(-.03em,.05em)!important}}';document.head.appendChild(s)}const social=document.querySelector('.social-links');if(social){social.innerHTML='<a class="social-btn" href="https://www.twitch.tv/YunaMyst" target="_blank" rel="noopener noreferrer" aria-label="Twitch"><img src="https://cdn.simpleicons.org/twitch/9146FF" alt="Twitch"></a><a class="social-btn" href="https://www.tiktok.com/@yunamyst_" target="_blank" rel="noopener noreferrer" aria-label="TikTok"><img src="https://cdn.simpleicons.org/tiktok/FFFFFF" alt="TikTok"></a><a class="social-btn" href="https://www.youtube.com/@YunaMyst" target="_blank" rel="noopener noreferrer" aria-label="YouTube"><img src="https://cdn.simpleicons.org/youtube/FF0000" alt="YouTube"></a>'}}
function card(code){return `<article class="code auto-code"><div class="gift">🎁</div><div class="cinfo"><strong>${esc(code)}</strong><small>🔄 Código ativo</small></div><div class="reward"><span class="scroll"></span><b>—</b><small>Recompensa</small></div><div class="reward"><span class="energy">⚡</span><b>—</b><small>Energia</small></div><div class="reward"><span class="mana"></span><b>—</b><small>Mana</small></div><button class="copy" type="button" data-code="${esc(code)}">▣ COPIAR</button><a class="link" href="${redeem}${encodeURIComponent(code)}" target="_blank" rel="noopener noreferrer">🔗 LINK</a></article>`}
function copyCode(code,b){const old=b.textContent,done=()=>{b.textContent='✓ COPIADO!';setTimeout(()=>b.textContent=old,1500)};if(navigator.clipboard&&window.isSecureContext)navigator.clipboard.writeText(code).then(done).catch(()=>fallback(code,b,old));else fallback(code,b,old)}
function fallback(code,b,old){try{const t=document.createElement('textarea');t.value=code;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();const ok=document.execCommand('copy');t.remove();if(ok){doneCopy(b,old);return}}catch(e){}window.prompt('Copie o código:',code)}
function doneCopy(b,old){b.textContent='✓ COPIADO!';setTimeout(()=>b.textContent=old,1500)}
function bindCopies(root=document){root.querySelectorAll('.copy[data-code]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();copyCode(b.dataset.code,b)})})}
async function loadCodes(){const active=document.getElementById('ativos');if(!active)return;removeBlockedFromIndex();try{const c=new AbortController(),timer=setTimeout(()=>c.abort(),7000),r=await fetch('./codes.json?ts='+Date.now(),{cache:'no-store',signal:c.signal});clearTimeout(timer);if(!r.ok)throw Error('codes.json');const data=await r.json();const codes=[...new Set((Array.isArray(data.codes)?data.codes:[]).map(normalize).filter(validCode))];if(codes.length)active.innerHTML=codes.map(card).join('');bindCopies(active);removeBlockedFromIndex();const s=document.querySelector('#sectionHead span');if(s)s.textContent='⟳ Atualizado automaticamente'}catch(e){console.warn('YunaMyst: codes.json indisponível; mantendo apenas códigos permitidos.',e);removeBlockedFromIndex();bindCopies(active)}removeStrayMarkupText()}
function setupPartnership(){const b=document.getElementById('partnershipBtn'),m=document.getElementById('parceriaModal'),x=document.getElementById('modalClose');if(b&&m&&!b.dataset.bound){b.dataset.bound=1;b.addEventListener('click',e=>{e.preventDefault();m.classList.add('open')})}if(x&&m&&!x.dataset.bound){x.dataset.bound=1;x.addEventListener('click',e=>{e.preventDefault();m.classList.remove('open')})}if(m&&!m.dataset.bound){m.dataset.bound=1;m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')})}}
function setupFAQ(){document.querySelectorAll('.faq-q').forEach(q=>{if(q.dataset.bound)return;q.dataset.bound=1;q.addEventListener('click',e=>{e.preventDefault();q.parentElement.classList.toggle('active')})})}
function setupLanguage(){const sw=document.getElementById('langSwitch'),t=document.getElementById('langToggle'),pt=document.getElementById('langPTOption'),en=document.getElementById('langENOption');if(!sw||!t)return;if(!t.dataset.bound){t.dataset.bound=1;t.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();sw.classList.toggle('open')})}const choose=lang=>{const isEN=lang==='en';document.documentElement.lang=isEN?'en':'pt-BR';t.innerHTML=isEN?'🇬🇧 ENG':'🇧🇷 PT/BR';if(pt)pt.classList.toggle('selected',!isEN);if(en)en.classList.toggle('selected',isEN);const nav=document.querySelectorAll('.navlinks a'),labels=isEN?['⌂ HOME','⚔ SUMMONERS WAR','❔ HOW TO USE']:['⌂ INÍCIO','⚔ SUMMONERS WAR','❔ COMO USAR'];nav.forEach((a,i)=>a.textContent=labels[i]);const p=document.querySelector('.community-tab.partnership strong');if(p)p.textContent=isEN?'🤝 PARTNERSHIP':'🤝 PARCERIA';const h=document.querySelector('.partnership-card h3'),tx=document.querySelector('.partnership-card p');if(h)h.textContent=isEN?'🤝 YUNAMYST PARTNERSHIP':'🤝 PARCERIA YUNAMYST';if(tx)tx.textContent=isEN?'Do you want to partner with YunaMyst Codes? This space is for creators, brands and projects related to Summoners War.':'Queres fazer uma parceria com o YunaMyst Codes? Este espaço é para criadores, marcas e projetos relacionados com Summoners War.';const ta=document.getElementById('tabAtivos'),te=document.getElementById('tabExpirados');if(ta)ta.textContent=isEN?'🟢 ACTIVE CODES':'🟢 CÓDIGOS ATIVOS';if(te)te.textContent=isEN?'🔴 EXPIRED CODES':'🔴 CÓDIGOS EXPIRADOS';document.querySelectorAll('#ativos .cinfo small').forEach(x=>x.textContent=isEN?'🔄 Active code':'🔄 Código ativo');document.querySelectorAll('#ativos .copy').forEach(x=>x.textContent=isEN?'▣ COPY':'▣ COPIAR');document.querySelectorAll('#expirados .cinfo small').forEach(x=>x.textContent=isEN?'Not available for redemption':'Não disponível para resgate');document.querySelectorAll('#expirados .badge-expired').forEach(x=>x.textContent=isEN?'⛔ EXPIRED':'⛔ EXPIRADO');const how=document.querySelector('.right> .panel h2');if(how)how.textContent=isEN?'❓ HOW TO USE':'❓ COMO USAR';try{localStorage.setItem('yunamyst-lang',lang)}catch(e){}sw.classList.remove('open')};let saved='pt';try{saved=localStorage.getItem('yunamyst-lang')||'pt'}catch(e){}choose(saved)}
function setupSound(){const a=document.getElementById('bgMusic'),b=document.getElementById('soundToggle');if(!a||!b||b.dataset.bound)return;b.dataset.bound='1';a.volume=window.matchMedia&&window.matchMedia('(max-width:850px)').matches ? 0.01 : 0.08;const key='yunamyst-mute-v3';try{a.muted=localStorage.getItem(key)==='1'}catch(e){a.muted=false}const sync=()=>{b.textContent=a.muted?'🔇':'🔊';b.title=a.muted?'Ativar música':'Silenciar música'};sync();b.addEventListener('click',e=>{e.preventDefault();a.muted=!a.muted;try{localStorage.setItem(key,a.muted?'1':'0')}catch(err){}if(!a.muted)a.play().catch(()=>{});sync()})}
function setupTabs(){const a=document.getElementById('ativos'),e=document.getElementById('expirados'),ta=document.getElementById('tabAtivos'),te=document.getElementById('tabExpirados');if(!a||!e||!ta||!te||te.dataset.bound)return;te.dataset.bound='1';ta.addEventListener('click',()=>{a.style.display='flex';e.style.display='none';ta.classList.add('active');te.classList.remove('active');history.replaceState(null,'','#codigos')});te.addEventListener('click',()=>{const open=e.style.display==='flex';a.style.display='flex';e.style.display=open?'none':'flex';ta.classList.toggle('active',open);te.classList.toggle('active',!open);history.replaceState(null,'',open?'#codigos':'#expirados')})}
function init(){fixBranding();removeStrayMarkupText();removeBlockedFromIndex();bindCopies();setupPartnership();setupFAQ();setupLanguage();setupSound();setupTabs();loadCodes()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
